<!-- Code generated by goweb-scaffold. DO NOT EDIT. -->
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';

import AppModal from '@/components/AppModal.vue';
import AppTable from '@/components/AppTable.vue';
import FormField from '@/components/FormField.vue';
import PermissionButton from '@/components/PermissionButton.vue';
import { deleteDemoNotice, fetchDemoNoticeDetail, fetchDemoNoticeList, saveDemoNotice, type DemoNoticeForm, type DemoNoticeItem } from '@/api/demo_notice';
import { formatTime, getErrorMessage, prettyJSON } from '@/helpers';
import { notifySuccess } from '@/notify';
import type { TableColumn } from '@/types';

type FieldOption = {
  label: string;
  value: any;
};

type FieldSchema = {
  field: string;
  label: string;
  component: string;
  display?: string;
  operator?: string;
  required?: boolean;
  readonly?: boolean;
  hidden?: boolean;
  searchable?: boolean;
  sortable?: boolean;
  placeholder?: string;
  width?: string;
  options?: FieldOption[];
  default_value?: any;
};

const listSchema: FieldSchema[] = [
  {
    "field": "id",
    "label": "ID",
    "component": "readonly-text",
    "display": "id",
    "sortable": true,
    "default_value": ""
  },
  {
    "field": "title",
    "label": "公告标题",
    "component": "text-input",
    "display": "text",
    "searchable": true,
    "sortable": true,
    "width": "220px",
    "default_value": ""
  },
  {
    "field": "status",
    "label": "状态",
    "component": "select",
    "display": "option-tag",
    "searchable": true,
    "sortable": true,
    "width": "120px",
    "options": [
      {
        "label": "草稿",
        "value": 0
      },
      {
        "label": "启用",
        "value": 1
      },
      {
        "label": "禁用",
        "value": 2
      }
    ],
    "default_value": 1
  },
  {
    "field": "sort",
    "label": "排序值",
    "component": "number-input",
    "display": "text",
    "sortable": true,
    "width": "100px",
    "default_value": 0
  },
  {
    "field": "created_at",
    "label": "创建时间",
    "component": "readonly-datetime",
    "display": "datetime",
    "sortable": true,
    "default_value": ""
  },
  {
    "field": "updated_at",
    "label": "更新时间",
    "component": "readonly-datetime",
    "display": "datetime",
    "sortable": true,
    "default_value": ""
  }
];
const formSchema: FieldSchema[] = [
  {
    "field": "title",
    "label": "公告标题",
    "component": "text-input",
    "required": true,
    "placeholder": "请输入公告标题",
    "width": "220px",
    "default_value": ""
  },
  {
    "field": "content",
    "label": "公告内容",
    "component": "textarea",
    "required": true,
    "placeholder": "请输入公告正文",
    "width": "360px",
    "default_value": ""
  },
  {
    "field": "status",
    "label": "状态",
    "component": "select",
    "required": true,
    "placeholder": "请选择状态",
    "width": "120px",
    "options": [
      {
        "label": "草稿",
        "value": 0
      },
      {
        "label": "启用",
        "value": 1
      },
      {
        "label": "禁用",
        "value": 2
      }
    ],
    "default_value": 1
  },
  {
    "field": "sort",
    "label": "排序值",
    "component": "number-input",
    "required": true,
    "placeholder": "请输入数字",
    "width": "100px",
    "default_value": 0
  }
];
const searchSchema: FieldSchema[] = [
  {
    "field": "title",
    "label": "公告标题",
    "component": "text-input",
    "operator": "like",
    "searchable": true,
    "placeholder": "请输入公告标题",
    "width": "220px",
    "default_value": ""
  },
  {
    "field": "status",
    "label": "状态",
    "component": "select",
    "operator": "eq",
    "searchable": true,
    "placeholder": "请选择状态",
    "width": "120px",
    "options": [
      {
        "label": "草稿",
        "value": 0
      },
      {
        "label": "启用",
        "value": 1
      },
      {
        "label": "禁用",
        "value": 2
      }
    ],
    "default_value": 1
  }
];
const columns: TableColumn[] = [
  {
    "key": "id",
    "title": "ID",
    "width": "80px"
  },
  {
    "key": "title",
    "title": "公告标题",
    "width": "220px"
  },
  {
    "key": "status",
    "title": "状态",
    "width": "120px"
  },
  {
    "key": "sort",
    "title": "排序值",
    "width": "100px"
  },
  {
    "key": "created_at",
    "title": "创建时间",
    "width": "180px"
  },
  {
    "key": "updated_at",
    "title": "更新时间",
    "width": "180px"
  },
  {
    "align": "right",
    "key": "actions",
    "title": "操作",
    "width": "220px"
  }
];
const defaultFormState = () => ({
  "content": "",
  "id": 0,
  "sort": 0,
  "status": 1,
  "title": ""
});
const defaultSearchState = () => ({
  "status": "",
  "title": ""
});

const rows = ref<DemoNoticeItem[]>([]);
const loading = ref(false);
const saving = ref(false);
const open = ref(false);
const errorMessage = ref('');
const total = ref(0);
const page = ref(1);
const pageSize = ref(10);
const form = reactive<Record<string, any>>(defaultFormState());
const searchForm = reactive<Record<string, any>>(defaultSearchState());

const modalTitle = computed(() => (form.id ? '编辑演示公告' : '新建演示公告'));
const totalPage = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)));
const visibleFormSchema = computed(() => formSchema.filter((item) => item.component !== 'hidden' && !item.hidden));

function resetForm() {
  Object.assign(form, defaultFormState());
}

function closeModal() {
  if (saving.value) {
    return;
  }
  open.value = false;
  resetForm();
}

function openCreate() {
  resetForm();
  open.value = true;
}

function normalizeFormValue(field: FieldSchema, value: unknown) {
  if (field.component === 'json-editor') {
    if (value == null || value === '') {
      return '{}';
    }
    return typeof value === 'string' ? value : prettyJSON(value);
  }
  if (field.component === 'datetime-picker' || field.component === 'readonly-datetime') {
    if (!value) {
      return '';
    }
    const date = new Date(String(value));
    if (Number.isNaN(date.getTime())) {
      return '';
    }
    return date.toISOString().slice(0, 16);
  }
  if (field.component === 'number-input') {
    return Number(value ?? 0);
  }
  if (field.component === 'switch') {
    return Boolean(value);
  }
  if (field.component === 'select' || field.component === 'radio') {
    return coerceOptionValue(field, value);
  }
  return value ?? '';
}

function coerceOptionValue(field: FieldSchema, value: unknown) {
  if (!field.options?.length) {
    return value;
  }
  for (const option of field.options) {
    if (option.value === value || String(option.value) === String(value)) {
      return option.value;
    }
  }
  return value;
}

function optionLabel(field: FieldSchema, value: unknown) {
  if (!field.options?.length) {
    return String(value ?? '-');
  }
  const matched = field.options.find((item) => item.value === value || String(item.value) === String(value));
  return matched?.label || String(value ?? '-');
}

async function load() {
  loading.value = true;
  errorMessage.value = '';
  try {
    const params: Record<string, unknown> = {
      page: page.value,
      page_size: pageSize.value,
    };

    for (const field of searchSchema) {
      if (field.component === 'datetime-range') {
        const start = String(searchForm[`${field.field}_start`] || '').trim();
        const end = String(searchForm[`${field.field}_end`] || '').trim();
        if (start) {
          params[`${field.field}_start`] = start;
        }
        if (end) {
          params[`${field.field}_end`] = end;
        }
        continue;
      }

      const raw = searchForm[field.field];
      if (field.component === 'number-input') {
        if (raw !== '' && raw !== null && raw !== undefined) {
          params[field.field] = Number(raw);
        }
        continue;
      }

      if (field.component === 'select') {
        if (raw !== '' && raw !== null && raw !== undefined) {
          params[field.field] = coerceOptionValue(field, raw);
        }
        continue;
      }

      const value = String(raw || '').trim();
      if (value) {
        params[field.field] = value;
      }
    }

    const result = await fetchDemoNoticeList(params);
    rows.value = result.list || [];
    total.value = result.total || 0;
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '加载演示公告列表失败');
  } finally {
    loading.value = false;
  }
}

async function openEdit(id: number) {
  errorMessage.value = '';
  try {
    const detail = await fetchDemoNoticeDetail(id);
    resetForm();
    form.id = detail.id;
    for (const field of formSchema) {
      form[field.field] = normalizeFormValue(field, detail[field.field as keyof DemoNoticeItem]);
    }
    open.value = true;
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '加载演示公告详情失败');
  }
}

function buildPayload() {
  const payload: Record<string, any> = {};
  if (form.id) {
    payload.id = Number(form.id);
  }
  for (const field of formSchema) {
    if (field.readonly || field.hidden || field.component === 'hidden') {
      continue;
    }
    const raw = form[field.field];
    switch (field.component) {
      case 'number-input':
        payload[field.field] = Number(raw || 0);
        break;
      case 'switch':
        payload[field.field] = Boolean(raw);
        break;
      case 'select':
      case 'radio':
        payload[field.field] = coerceOptionValue(field, raw);
        break;
      case 'json-editor':
        if (!String(raw || '').trim()) {
          payload[field.field] = {};
          break;
        }
        payload[field.field] = JSON.parse(String(raw));
        break;
      case 'datetime-picker':
        payload[field.field] = String(raw || '').trim();
        break;
      default:
        payload[field.field] = typeof raw === 'string' ? raw.trim() : raw;
        break;
    }
  }
  return payload as DemoNoticeForm;
}

async function submit() {
  saving.value = true;
  errorMessage.value = '';
  try {
    await saveDemoNotice(buildPayload());
    notifySuccess(form.id ? '演示公告已更新' : '演示公告已创建');
    open.value = false;
    resetForm();
    await load();
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '保存演示公告失败');
  } finally {
    saving.value = false;
  }
}

async function removeRow(row: DemoNoticeItem) {
  if (!window.confirm(`确认删除「${String(row.id)}」对应的演示公告记录吗？`)) {
    return;
  }
  try {
    await deleteDemoNotice(row.id);
    if (rows.value.length === 1 && page.value > 1) {
      page.value -= 1;
    }
    notifySuccess('演示公告已删除');
    await load();
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '删除演示公告失败');
  }
}

async function search() {
  page.value = 1;
  await load();
}

async function goPage(next: number) {
  if (next < 1 || next > totalPage.value || next === page.value) {
    return;
  }
  page.value = next;
  await load();
}

function renderBooleanLabel(field: string, value: unknown) {
  if (field.includes('status')) {
    return Number(value) === 1 ? '启用' : '禁用';
  }
  return value ? '是' : '否';
}

function renderJSONPreview(value: unknown) {
  const text = prettyJSON(value);
  return text.length > 80 ? `${text.slice(0, 80)}...` : text;
}

function fieldByName(fieldName: string) {
  return listSchema.find((item) => item.field === fieldName) || formSchema.find((item) => item.field === fieldName);
}

onMounted(load);
</script>

<template>
  <section class="page-stack">
    <article class="card page-card">
      <div class="section-heading">
        <div>
          <h3>演示公告</h3>
          <p>生成器输出的后台 CRUD 页面，支持搜索、列表、弹窗编辑和按钮权限控制。</p>
        </div>
        <PermissionButton code="demo_notice.save">
          <button class="btn" type="button" @click="openCreate">新建演示公告</button>
        </PermissionButton>
      </div>

      <div v-if="errorMessage" class="error-banner">{{ errorMessage }}</div>

      <div class="form-grid two-columns">
        <FormField
          v-for="field in searchSchema"
          :key="field.field"
          :label="field.label"
        >
          <template v-if="field.component === 'datetime-range'">
            <div class="form-grid two-columns">
              <input
                v-model="searchForm[`${field.field}_start`]"
                class="input"
                type="datetime-local"
                :placeholder="field.placeholder || '开始时间'"
              />
              <input
                v-model="searchForm[`${field.field}_end`]"
                class="input"
                type="datetime-local"
                :placeholder="field.placeholder || '结束时间'"
              />
            </div>
          </template>
          <select
            v-else-if="field.component === 'select'"
            v-model="searchForm[field.field]"
            class="input"
          >
            <option value="">全部</option>
            <option v-for="option in field.options || []" :key="`${field.field}-${String(option.value)}`" :value="option.value">
              {{ option.label }}
            </option>
          </select>
          <input
            v-else-if="field.component === 'number-input'"
            v-model="searchForm[field.field]"
            class="input"
            type="number"
            :placeholder="field.placeholder || `请输入${field.label}`"
          />
          <input
            v-else
            v-model="searchForm[field.field]"
            class="input"
            :placeholder="field.placeholder || `搜索${field.label}`"
          />
        </FormField>
      </div>

      <div class="table-footer">
        <div class="text-muted">共 {{ total }} 条记录</div>
        <div class="table-actions">
          <button class="btn secondary" type="button" @click="search">查询</button>
        </div>
      </div>
    </article>

    <article class="card page-card">
      <AppTable :columns="columns" :rows="rows" :loading="loading" empty-text="暂无演示公告数据">
        <template #cell-created_at="{ value }">
          {{ formatTime(value) }}
        </template>
        <template #cell-updated_at="{ value }">
          {{ formatTime(value) }}
        </template>
        <template
          v-for="field in listSchema"
          :key="field.field"
          #[`cell-${field.field}`]="{ value }"
        >
          <span v-if="field.display === 'datetime'">{{ formatTime(String(value || '')) }}</span>
          <span v-else-if="field.display === 'boolean-tag'" class="status-pill" :class="value ? 'is-active' : 'is-disabled'">
            {{ renderBooleanLabel(field.field, value) }}
          </span>
          <span v-else-if="field.display === 'option-tag'" class="status-pill is-info">
            {{ optionLabel(fieldByName(field.field) || field, value) }}
          </span>
          <code v-else-if="field.display === 'json-preview'">{{ renderJSONPreview(value) }}</code>
          <span v-else>{{ value ?? '-' }}</span>
        </template>
        <template #cell-actions="{ row }">
          <div class="table-actions">
            <PermissionButton code="demo_notice.save">
              <button class="btn secondary btn-sm" type="button" @click="openEdit(Number(row.id))">编辑</button>
            </PermissionButton>
            <PermissionButton code="demo_notice.delete">
              <button class="btn danger btn-sm" type="button" @click="removeRow(row)">删除</button>
            </PermissionButton>
          </div>
        </template>
      </AppTable>

      <div class="table-footer">
        <div class="text-muted">第 {{ page }} / {{ totalPage }} 页</div>
        <div class="table-actions">
          <button class="btn secondary" type="button" :disabled="page <= 1" @click="goPage(page - 1)">上一页</button>
          <button class="btn secondary" type="button" :disabled="page >= totalPage" @click="goPage(page + 1)">下一页</button>
        </div>
      </div>
    </article>

    <AppModal :open="open" :title="modalTitle" width="760px" @close="closeModal">
      <div class="form-grid two-columns">
        <FormField
          v-for="field in visibleFormSchema"
          :key="field.field"
          :label="field.label"
          :required="field.required"
          :hint="field.placeholder"
        >
          <textarea
            v-if="field.component === 'textarea' || field.component === 'json-editor'"
            v-model="form[field.field]"
            class="input textarea"
            :placeholder="field.placeholder || `请输入${field.label}`"
            :readonly="field.readonly"
          />
          <input
            v-else-if="field.component === 'number-input'"
            v-model="form[field.field]"
            class="input"
            type="number"
            :placeholder="field.placeholder || `请输入${field.label}`"
            :readonly="field.readonly"
          />
          <select
            v-else-if="field.component === 'select'"
            v-model="form[field.field]"
            class="input"
            :disabled="field.readonly"
          >
            <option v-if="!field.required" value="">请选择</option>
            <option v-for="option in field.options || []" :key="`${field.field}-${String(option.value)}`" :value="option.value">
              {{ option.label }}
            </option>
          </select>
          <div v-else-if="field.component === 'radio'" class="check-grid">
            <label
              v-for="option in field.options || []"
              :key="`${field.field}-${String(option.value)}`"
              class="check-card"
            >
              <input
                v-model="form[field.field]"
                :value="option.value"
                type="radio"
                :disabled="field.readonly"
              />
              <span>{{ option.label }}</span>
            </label>
          </div>
          <label v-else-if="field.component === 'switch'" class="checkbox-item">
            <input v-model="form[field.field]" type="checkbox" :disabled="field.readonly" />
            <span>{{ form[field.field] ? '启用' : '禁用' }}</span>
          </label>
          <input
            v-else-if="field.component === 'datetime-picker' || field.component === 'readonly-datetime'"
            v-model="form[field.field]"
            class="input"
            type="datetime-local"
            :readonly="field.readonly || field.component === 'readonly-datetime'"
          />
          <input
            v-else
            v-model="form[field.field]"
            class="input"
            :placeholder="field.placeholder || `请输入${field.label}`"
            :readonly="field.readonly || field.component === 'readonly-text'"
          />
        </FormField>
      </div>

      <template #footer>
        <div class="modal-actions">
          <button class="btn secondary" type="button" :disabled="saving" @click="closeModal">取消</button>
          <button class="btn" type="button" :disabled="saving" @click="submit">保存</button>
        </div>
      </template>
    </AppModal>
  </section>
</template>
