<!-- Code generated by goweb-scaffold. DO NOT EDIT. -->
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';

import AppModal from '@/components/AppModal.vue';
import AppTable from '@/components/AppTable.vue';
import FormField from '@/components/FormField.vue';
import PermissionButton from '@/components/PermissionButton.vue';
import { deleteDemoArticle, fetchDemoArticleDetail, fetchDemoArticleList, saveDemoArticle, type DemoArticleForm, type DemoArticleItem } from '@/api/demo_article';
import { formatTime, getErrorMessage, prettyJSON } from '@/helpers';
import { notifySuccess } from '@/notify';
import type { TableColumn } from '@/types';

type FieldSchema = {
  field: string;
  label: string;
  component: string;
  display?: string;
  operator?: string;
  required?: boolean;
  readonly?: boolean;
  hidden?: boolean;
  searchable?: boolean;
  sortable?: boolean;
  placeholder?: string;
};

const listSchema: FieldSchema[] = [
  {
    "field": "id",
    "label": "ID",
    "component": "",
    "display": "id",
    "sortable": true
  },
  {
    "field": "title",
    "label": "Title",
    "component": "",
    "display": "text",
    "searchable": true,
    "sortable": true
  },
  {
    "field": "summary",
    "label": "Summary",
    "component": "",
    "display": "text",
    "searchable": true
  },
  {
    "field": "status",
    "label": "Status",
    "component": "",
    "display": "text",
    "searchable": true,
    "sortable": true
  },
  {
    "field": "sort",
    "label": "Sort",
    "component": "",
    "display": "text",
    "sortable": true
  },
  {
    "field": "created_at",
    "label": "创建时间",
    "component": "",
    "display": "datetime",
    "sortable": true
  },
  {
    "field": "updated_at",
    "label": "更新时间",
    "component": "",
    "display": "datetime",
    "sortable": true
  }
];
const formSchema: FieldSchema[] = [
  {
    "field": "title",
    "label": "Title",
    "component": "text-input",
    "required": true,
    "placeholder": "请输入Title"
  },
  {
    "field": "summary",
    "label": "Summary",
    "component": "textarea",
    "required": true,
    "placeholder": "请输入详细内容"
  },
  {
    "field": "status",
    "label": "Status",
    "component": "number-input",
    "required": true,
    "placeholder": "请输入数字"
  },
  {
    "field": "sort",
    "label": "Sort",
    "component": "number-input",
    "required": true,
    "placeholder": "请输入数字"
  }
];
const searchSchema: FieldSchema[] = [
  {
    "field": "title",
    "label": "Title",
    "component": "text-input",
    "operator": "like",
    "searchable": true
  },
  {
    "field": "status",
    "label": "Status",
    "component": "number-input",
    "operator": "eq",
    "searchable": true
  }
];
const columns: TableColumn[] = [
  {
    "key": "id",
    "title": "ID",
    "width": "80px"
  },
  {
    "key": "title",
    "title": "Title"
  },
  {
    "key": "summary",
    "title": "Summary"
  },
  {
    "key": "status",
    "title": "Status"
  },
  {
    "key": "sort",
    "title": "Sort"
  },
  {
    "key": "created_at",
    "title": "创建时间",
    "width": "180px"
  },
  {
    "key": "updated_at",
    "title": "更新时间",
    "width": "180px"
  },
  {
    "align": "right",
    "key": "actions",
    "title": "操作",
    "width": "220px"
  }
];
const defaultFormState = () => ({
  "id": 0,
  "sort": 0,
  "status": 1,
  "summary": "",
  "title": ""
});
const defaultSearchState = () => ({
  "status": "",
  "title": ""
});

const rows = ref<DemoArticleItem[]>([]);
const loading = ref(false);
const saving = ref(false);
const open = ref(false);
const errorMessage = ref('');
const total = ref(0);
const page = ref(1);
const pageSize = ref(10);
const form = reactive<Record<string, any>>(defaultFormState());
const searchForm = reactive<Record<string, any>>(defaultSearchState());

const modalTitle = computed(() => (form.id ? '编辑演示文章' : '新建演示文章'));
const totalPage = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)));
const visibleFormSchema = computed(() => formSchema.filter((item) => !item.hidden));

function resetForm() {
  Object.assign(form, defaultFormState());
}

function closeModal() {
  if (saving.value) {
    return;
  }
  open.value = false;
  resetForm();
}

function openCreate() {
  resetForm();
  open.value = true;
}

function normalizeFormValue(field: FieldSchema, value: unknown) {
  if (field.component === 'json-editor') {
    if (value == null || value === '') {
      return '{}';
    }
    return typeof value === 'string' ? value : prettyJSON(value);
  }
  if (field.component === 'datetime-picker' || field.component === 'readonly-datetime') {
    if (!value) {
      return '';
    }
    const date = new Date(String(value));
    if (Number.isNaN(date.getTime())) {
      return '';
    }
    return date.toISOString().slice(0, 16);
  }
  if (field.component === 'number-input') {
    return Number(value ?? 0);
  }
  if (field.component === 'switch') {
    return Boolean(value);
  }
  return value ?? '';
}

async function load() {
  loading.value = true;
  errorMessage.value = '';
  try {
    const params: Record<string, unknown> = {
      page: page.value,
      page_size: pageSize.value,
    };

    for (const field of searchSchema) {
      if (field.component === 'datetime-range') {
        const start = String(searchForm[`${field.field}_start`] || '').trim();
        const end = String(searchForm[`${field.field}_end`] || '').trim();
        if (start) {
          params[`${field.field}_start`] = start;
        }
        if (end) {
          params[`${field.field}_end`] = end;
        }
        continue;
      }

      const raw = searchForm[field.field];
      if (field.component === 'number-input') {
        if (raw !== '' && raw !== null && raw !== undefined) {
          params[field.field] = Number(raw);
        }
        continue;
      }

      if (field.component === 'select') {
        if (raw !== '' && raw !== null && raw !== undefined) {
          params[field.field] = raw;
        }
        continue;
      }

      const value = String(raw || '').trim();
      if (value) {
        params[field.field] = value;
      }
    }

    const result = await fetchDemoArticleList(params);
    rows.value = result.list || [];
    total.value = result.total || 0;
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '加载演示文章列表失败');
  } finally {
    loading.value = false;
  }
}

async function openEdit(id: number) {
  errorMessage.value = '';
  try {
    const detail = await fetchDemoArticleDetail(id);
    resetForm();
    form.id = detail.id;
    for (const field of formSchema) {
      form[field.field] = normalizeFormValue(field, detail[field.field as keyof DemoArticleItem]);
    }
    open.value = true;
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '加载演示文章详情失败');
  }
}

function buildPayload() {
  const payload: Record<string, any> = {};
  if (form.id) {
    payload.id = Number(form.id);
  }
  for (const field of formSchema) {
    if (field.readonly || field.hidden) {
      continue;
    }
    const raw = form[field.field];
    switch (field.component) {
      case 'number-input':
        payload[field.field] = Number(raw || 0);
        break;
      case 'switch':
        payload[field.field] = Boolean(raw);
        break;
      case 'json-editor':
        if (!String(raw || '').trim()) {
          payload[field.field] = {};
          break;
        }
        payload[field.field] = JSON.parse(String(raw));
        break;
      case 'datetime-picker':
        payload[field.field] = String(raw || '').trim();
        break;
      default:
        payload[field.field] = typeof raw === 'string' ? raw.trim() : raw;
        break;
    }
  }
  return payload as DemoArticleForm;
}

async function submit() {
  saving.value = true;
  errorMessage.value = '';
  try {
    await saveDemoArticle(buildPayload());
    notifySuccess(form.id ? '演示文章已更新' : '演示文章已创建');
    open.value = false;
    resetForm();
    await load();
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '保存演示文章失败');
  } finally {
    saving.value = false;
  }
}

async function removeRow(row: DemoArticleItem) {
  if (!window.confirm(`确认删除「${String(row.id)}」对应的演示文章记录吗？`)) {
    return;
  }
  try {
    await deleteDemoArticle(row.id);
    if (rows.value.length === 1 && page.value > 1) {
      page.value -= 1;
    }
    notifySuccess('演示文章已删除');
    await load();
  } catch (error) {
    errorMessage.value = getErrorMessage(error, '删除演示文章失败');
  }
}

async function search() {
  page.value = 1;
  await load();
}

async function goPage(next: number) {
  if (next < 1 || next > totalPage.value || next === page.value) {
    return;
  }
  page.value = next;
  await load();
}

function renderBooleanLabel(field: string, value: unknown) {
  if (field.includes('status')) {
    return Number(value) === 1 ? '启用' : '禁用';
  }
  return value ? '是' : '否';
}

function renderJSONPreview(value: unknown) {
  const text = prettyJSON(value);
  return text.length > 80 ? `${text.slice(0, 80)}...` : text;
}

onMounted(load);
</script>

<template>
  <section class="page-stack">
    <article class="card page-card">
      <div class="section-heading">
        <div>
          <h3>演示文章管理</h3>
          <p>该页面由 codegen 生成，提供正式可用的后台 CRUD 基础能力。</p>
        </div>
        <PermissionButton code="demo_article.save">
          <button class="btn" type="button" @click="openCreate">新建演示文章</button>
        </PermissionButton>
      </div>

      <div class="toolbar-row">
        <div class="search-grid">
          <FormField
            v-for="field in searchSchema"
            :key="field.field"
            :label="field.label"
          >
            <div v-if="field.component === 'datetime-range'" class="inline-range">
              <input
                v-model="searchForm[`${field.field}_start`]"
                class="input"
                type="datetime-local"
              />
              <input
                v-model="searchForm[`${field.field}_end`]"
                class="input"
                type="datetime-local"
              />
            </div>
            <select v-else-if="field.component === 'select'" v-model="searchForm[field.field]" class="input">
              <option value="">全部</option>
              <option :value="true">是</option>
              <option :value="false">否</option>
            </select>
            <input
              v-else-if="field.component === 'number-input'"
              v-model.number="searchForm[field.field]"
              class="input"
              type="number"
              :placeholder="field.placeholder || `请输入${field.label}`"
            />
            <input
              v-else
              v-model="searchForm[field.field]"
              class="input"
              :placeholder="field.placeholder || `请输入${field.label}`"
              @keyup.enter="search"
            />
          </FormField>
        </div>
        <div class="table-actions">
          <button class="btn secondary" type="button" @click="search">搜索</button>
        </div>
      </div>

      <div class="toolbar-row">
        <span class="text-muted">共 <strong v-text="total" /> 条</span>
      </div>

      <p v-if="errorMessage" class="error-banner" v-text="errorMessage" />

      <AppTable :columns="columns" :rows="rows" :loading="loading" empty-text="暂无数据">
        <template #cell-created_at="{ value }">
          <span v-text="formatTime(value)" />
        </template>
        <template #cell-updated_at="{ value }">
          <span v-text="formatTime(value)" />
        </template>
        <template #cell-actions="{ row }">
          <div class="table-actions">
            <PermissionButton code="demo_article.save">
              <button class="btn secondary btn-sm" type="button" @click="openEdit(row.id)">编辑</button>
            </PermissionButton>
            <PermissionButton code="demo_article.delete">
              <button class="btn danger btn-sm" type="button" @click="removeRow(row)">删除</button>
            </PermissionButton>
          </div>
        </template>
      </AppTable>

      <div class="table-footer">
        <span>第 <strong v-text="page" /> / <strong v-text="totalPage" /> 页</span>
        <div class="table-actions">
          <button class="btn secondary btn-sm" type="button" :disabled="page <= 1" @click="goPage(page - 1)">上一页</button>
          <button class="btn secondary btn-sm" type="button" :disabled="page >= totalPage" @click="goPage(page + 1)">下一页</button>
        </div>
      </div>
    </article>

    <AppModal
      :open="open"
      :title="modalTitle"
      width="760px"
      :mask-closable="!saving"
      :esc-closable="!saving"
      @close="closeModal"
    >
      <div class="form-grid two-columns">
        <FormField
          v-for="field in visibleFormSchema"
          :key="field.field"
          :label="field.label"
          :required="field.required"
          :hint="field.placeholder"
        >
          <textarea
            v-if="field.component === 'textarea' || field.component === 'json-editor'"
            v-model="form[field.field]"
            class="input textarea"
            :readonly="field.readonly"
          />
          <select
            v-else-if="field.component === 'switch'"
            v-model="form[field.field]"
            class="input"
            :disabled="field.readonly"
          >
            <option :value="true">是</option>
            <option :value="false">否</option>
          </select>
          <input
            v-else-if="field.component === 'number-input'"
            v-model.number="form[field.field]"
            class="input"
            type="number"
            :readonly="field.readonly"
          />
          <input
            v-else-if="field.component === 'datetime-picker' || field.component === 'readonly-datetime'"
            v-model="form[field.field]"
            class="input"
            type="datetime-local"
            :readonly="field.readonly"
          />
          <input
            v-else
            v-model="form[field.field]"
            class="input"
            :readonly="field.readonly"
          />
        </FormField>
      </div>

      <template #footer>
        <div class="table-actions">
          <button class="btn secondary" type="button" :disabled="saving" @click="closeModal">取消</button>
          <button class="btn" type="button" :disabled="saving" @click="submit">
            <span v-if="saving">提交中...</span>
            <span v-else>保存</span>
          </button>
        </div>
      </template>
    </AppModal>
  </section>
</template>
