// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

import (
	"strconv"
	"strings"

	"github.com/lvjiaben/goweb-core/httpx"
	"github.com/lvjiaben/goweb-scaffold/internal/bootstrap"
)

type Module struct{}

func (Module) Name() string { return GeneratedModuleName }

func (Module) Register(runtime *bootstrap.Runtime) error {
	group := runtime.BackendProtectedGroup.Group("/app/demo_article")
	group.GET("/list", list(runtime), httpx.WithPermission("demo_article.list"))
	group.GET("/detail", detail(runtime), httpx.WithPermission("demo_article.list"))
	group.POST("/save", save(runtime), httpx.WithPermission("demo_article.save"))
	group.POST("/delete", deleteRows(runtime), httpx.WithPermission("demo_article.delete"))
	return nil
}

func list(runtime *bootstrap.Runtime) httpx.HandlerFunc {
	return func(c *httpx.Context) {
		page, pageSize := bootstrap.Pagination(c)
		filters := bootstrap.ParseFilter(c)
		query := runtime.DB.Model(&Entity{}).Order("id DESC")
		if keyword := bootstrap.SearchKeyword(c); keyword != "" {
			likeValue := bootstrap.LikeKeyword(keyword)
			query = query.Where("title ILIKE ?",
				likeValue,
			)
		}
		if value := bootstrap.FilterString(filters, "title"); value != "" {
			query = query.Where("title ILIKE ?", bootstrap.LikeKeyword(value))
		}
		if raw := bootstrap.FilterString(filters, "status"); raw != "" {
			value, err := strconv.Atoi(raw)
			if err != nil {
				c.BadRequest("status must be an integer value")
				return
			}
			query = query.Where("status = ?", value)
		}

		var total int64
		if err := query.Count(&total).Error; err != nil {
			c.Error(err)
			return
		}

		var rows []Entity
		if err := query.Offset((page - 1) * pageSize).Limit(pageSize).Find(&rows).Error; err != nil {
			c.Error(err)
			return
		}

		c.Success(bootstrap.PagedResult(rows, total, page, pageSize))
	}
}

func detail(runtime *bootstrap.Runtime) httpx.HandlerFunc {
	return func(c *httpx.Context) {
		id, err := c.QueryInt64("id")
		if err != nil || id <= 0 {
			c.BadRequest("invalid id")
			return
		}

		var row Entity
		if err := runtime.DB.First(&row, id).Error; err != nil {
			c.Error(err)
			return
		}

		c.Success(row)
	}
}

func save(runtime *bootstrap.Runtime) httpx.HandlerFunc {
	return func(c *httpx.Context) {
		var req SaveRequest
		if err := c.BindJSON(&req); err != nil {
			c.Error(err)
			return
		}
		if strings.TrimSpace(req.Title) == "" {
			c.BadRequest("title is required")
			return
		}
		if strings.TrimSpace(req.Summary) == "" {
			c.BadRequest("summary is required")
			return
		}

		var row Entity
		if req.ID > 0 {
			if err := runtime.DB.First(&row, req.ID).Error; err != nil {
				c.Error(err)
				return
			}
		}
		row.Title = strings.TrimSpace(req.Title)
		row.Summary = strings.TrimSpace(req.Summary)
		row.Status = req.Status
		row.Sort = req.Sort

		if req.ID == 0 {
			if err := runtime.DB.Create(&row).Error; err != nil {
				c.Error(err)
				return
			}
		} else {
			if err := runtime.DB.Save(&row).Error; err != nil {
				c.Error(err)
				return
			}
		}

		c.Success(map[string]any{"id": row.ID})
	}
}

func deleteRows(runtime *bootstrap.Runtime) httpx.HandlerFunc {
	return func(c *httpx.Context) {
		var req bootstrap.IDsPayload
		if err := c.BindJSON(&req); err != nil {
			c.Error(err)
			return
		}

		ids := req.Values()
		if len(ids) == 0 {
			c.BadRequest("ids is required")
			return
		}

		if err := runtime.DB.Where("id IN ?", ids).Delete(&Entity{}).Error; err != nil {
			c.Error(err)
			return
		}

		c.Success(map[string]any{"deleted": len(ids)})
	}
}
