// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

type SaveRequest struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Summary string `json:"summary"`
	Status  int    `json:"status"`
	Sort    int    `json:"sort"`
}

type ListItem = Entity

type DetailItem = Entity
