// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

const (
	GeneratedModuleName = "demo_article"
	GeneratedTableName  = "demo_article"
	GeneratedRoutePath  = "/system/demo-article"
	GeneratedPageName   = "DemoArticleList"
	GeneratedViewFile   = "views/demo_article/list.vue"
	GeneratedMenuTitle  = "演示文章"
)

var GeneratedPermissionCodes = []string{
	"demo_article.list",
	"demo_article.save",
	"demo_article.delete",
}
