// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

import (
	"gorm.io/gorm"
	"time"
)

type Entity struct {
	ID        int64          `gorm:"primaryKey;column:id" json:"id"`
	Title     string         `gorm:"column:title" json:"title"`
	Summary   string         `gorm:"column:summary" json:"summary"`
	Status    int            `gorm:"column:status" json:"status"`
	Sort      int            `gorm:"column:sort" json:"sort"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;index" json:"deleted_at"`
}

func (Entity) TableName() string {
	return "demo_article"
}
