// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

import (
	sharedmodel "github.com/lvjiaben/goweb-scaffold/internal/shared/model"
)

type Entity struct {
	sharedmodel.BaseModel
	Title   string `gorm:"column:title" json:"title"`
	Summary string `gorm:"column:summary" json:"summary"`
	Status  int    `gorm:"column:status" json:"status"`
	Sort    int    `gorm:"column:sort" json:"sort"`
}

func (Entity) TableName() string {
	return "demo_article"
}
