// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

import (
	"github.com/lvjiaben/goweb-core/httpx"
	"github.com/lvjiaben/goweb-scaffold/internal/bootstrap"
)

type Module struct{}

func (Module) Name() string { return GeneratedModuleName }

func (Module) Register(runtime *bootstrap.Runtime) error {
	group := runtime.BackendProtectedGroup.Group("/app/demo_article")
	group.GET("/list", list(runtime), httpx.WithPermission("demo_article.list"))
	group.GET("/detail", detail(runtime), httpx.WithPermission("demo_article.list"))
	group.POST("/save", save(runtime), httpx.WithPermission("demo_article.save"))
	group.POST("/delete", deleteRows(runtime), httpx.WithPermission("demo_article.delete"))
	return nil
}
