// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_article

import (
	"strconv"
	"strings"

	"github.com/lvjiaben/goweb-scaffold/internal/bootstrap"
)

type Service struct {
	repo *Repo
}

func NewService(runtime *bootstrap.Runtime) *Service {
	return &Service{repo: NewRepo(runtime)}
}

func (s *Service) List(params ListParams) (map[string]any, error) {
	filter, err := s.buildListFilter(params)
	if err != nil {
		return nil, err
	}
	total, err := s.repo.Count(filter)
	if err != nil {
		return nil, err
	}
	rows, err := s.repo.List(filter, params.Page, params.PageSize)
	if err != nil {
		return nil, err
	}
	return bootstrap.PagedResult(rows, total, params.Page, params.PageSize), nil
}

func (s *Service) Detail(id int64) (DetailItem, error) {
	row, err := s.repo.FindByID(id)
	if err != nil {
		return DetailItem{}, err
	}
	return row, nil
}

func (s *Service) SaveRecord(req SaveRequest) (SaveResult, error) {
	if err := validateSaveRequest(req); err != nil {
		return SaveResult{}, err
	}

	row := Entity{}
	if req.ID > 0 {
		existing, err := s.repo.FindByID(req.ID)
		if err != nil {
			return SaveResult{}, err
		}
		row = existing
	}
	row.Title = strings.TrimSpace(req.Title)
	row.Summary = strings.TrimSpace(req.Summary)
	row.Status = req.Status
	row.Sort = req.Sort

	if req.ID == 0 {
		if err := s.repo.Create(&row); err != nil {
			return SaveResult{}, err
		}
	} else {
		if err := s.repo.Save(&row); err != nil {
			return SaveResult{}, err
		}
	}
	return SaveResult{ID: row.ID}, nil
}

func (s *Service) DeleteRows(ids []int64) (DeleteResult, error) {
	ids = normalizeIDs(ids...)
	if len(ids) == 0 {
		return DeleteResult{}, validationError("ids is required")
	}
	if err := s.repo.DeleteByIDs(ids); err != nil {
		return DeleteResult{}, err
	}
	return DeleteResult{Deleted: len(ids)}, nil
}

func (s *Service) buildListFilter(params ListParams) (ListFilter, error) {
	filter := ListFilter{
		Keyword: bootstrap.LikeKeyword(params.Keyword),
		Like:    map[string]string{},
		Exact:   map[string]any{},
		Range:   map[string]timeRange{},
	}
	if value := bootstrap.FilterString(params.Filters, "title"); value != "" {
		filter.Like["title"] = bootstrap.LikeKeyword(value)
	}
	if raw := bootstrap.FilterString(params.Filters, "status"); raw != "" {
		value, err := strconv.Atoi(raw)
		if err != nil {
			return filter, validationError("status must be an integer value")
		}
		filter.Exact["status"] = value
	}
	return filter, nil
}

func validateSaveRequest(req SaveRequest) error {
	if strings.TrimSpace(req.Title) == "" {
		return validationError("title is required")
	}
	if strings.TrimSpace(req.Summary) == "" {
		return validationError("summary is required")
	}
	return nil
}

func normalizeIDs(values ...int64) []int64 {
	seen := make(map[int64]struct{}, len(values))
	out := make([]int64, 0, len(values))
	for _, value := range values {
		if value <= 0 {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

type validationError string

func (e validationError) Error() string {
	return string(e)
}

func isValidationError(err error) bool {
	_, ok := err.(validationError)
	return ok
}
