// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_notice

const (
	GeneratedModuleName = "demo_notice"
	GeneratedTableName  = "demo_notice"
	GeneratedRoutePath  = "/system/demo-notice"
	GeneratedPageName   = "DemoNoticePage"
	GeneratedMenuTitle  = "演示公告"
)

var GeneratedPermissionCodes = []string{
	"demo_notice.list",
	"demo_notice.save",
	"demo_notice.delete",
}
