// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_notice

import (
	"github.com/lvjiaben/goweb-core/httpx"
	"github.com/lvjiaben/goweb-scaffold/internal/bootstrap"
)

type Module struct{}

func (Module) Name() string { return GeneratedModuleName }

func (Module) Register(runtime *bootstrap.Runtime) error {
	group := runtime.BackendProtectedGroup.Group("/app/demo_notice")
	group.GET("/list", list(runtime), httpx.WithPermission("demo_notice.list"))
	group.GET("/detail", detail(runtime), httpx.WithPermission("demo_notice.list"))
	group.POST("/save", save(runtime), httpx.WithPermission("demo_notice.save"))
	group.POST("/delete", deleteRows(runtime), httpx.WithPermission("demo_notice.delete"))
	return nil
}
