// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_notice

import (
	"time"

	"github.com/lvjiaben/goweb-scaffold/internal/bootstrap"
	sharedquery "github.com/lvjiaben/goweb-scaffold/internal/shared/query"
	"gorm.io/gorm"
)

type Repo struct {
	db *gorm.DB
}

func NewRepo(runtime *bootstrap.Runtime) *Repo {
	return &Repo{db: runtime.DB}
}

func (r *Repo) Count(filter ListFilter) (int64, error) {
	var total int64
	err := r.applyListFilter(r.db.Model(&Entity{}), filter).Count.Count(&total).Error
	return total, err
}

func (r *Repo) List(filter ListFilter, page int, pageSize int) ([]Entity, error) {
	var rows []Entity
	result := r.applyListFilter(r.db.Model(&Entity{}), filter)
	err := result.Query.Offset((page - 1) * pageSize).Limit(pageSize).Find(&rows).Error
	return rows, err
}

func (r *Repo) FindByID(id int64) (Entity, error) {
	var row Entity
	err := r.db.First(&row, id).Error
	return row, err
}

func (r *Repo) Create(row *Entity) error {
	return r.db.Create(row).Error
}

func (r *Repo) Save(row *Entity) error {
	return r.db.Save(row).Error
}

func (r *Repo) DeleteByIDs(ids []int64) error {
	return r.db.Where("id IN ?", ids).Delete(&Entity{}).Error
}

func (r *Repo) applyListFilter(query *gorm.DB, filter ListFilter) sharedquery.Result {
	return sharedquery.Apply(query, sharedquery.Params{
		Search:    filter.Keyword,
		Filters:   filter.ToFilters(),
		SortBy:    filter.SortBy,
		SortOrder: filter.SortOrder,
	}, sharedquery.Options{
		SearchFields: []string{"title"},
		LikeFields:   []string{"title"},
		ExactFields:  []string{"status"},
		RangeFields:  []string{},
		AllowedSorts: []string{"id", "title", "content", "status", "sort", "created_at", "updated_at", "deleted_at"},
		DefaultSorts: sharedquery.DefaultSorts("id", "title", "content", "status", "sort", "created_at", "updated_at", "deleted_at"),
	})
}

type ListFilter struct {
	Keyword   string
	Like      map[string]string
	Exact     map[string]any
	Range     map[string]timeRange
	SortBy    string
	SortOrder string
}

type timeRange struct {
	Start *time.Time
	End   *time.Time
}

func (f ListFilter) ToFilters() map[string]any {
	result := map[string]any{}
	for k, v := range f.Like {
		result[k] = v
	}
	for k, v := range f.Exact {
		result[k] = v
	}
	for k, v := range f.Range {
		if v.Start != nil {
			result[k+"_from"] = v.Start.Format(time.RFC3339)
		}
		if v.End != nil {
			result[k+"_to"] = v.End.Format(time.RFC3339)
		}
	}
	return result
}
