// Code generated by goweb-scaffold. DO NOT EDIT.

package demo_notice

import "github.com/lvjiaben/goweb-scaffold/internal/bootstrap"

type Service struct {
	repo *Repo
}

func NewService(runtime *bootstrap.Runtime) *Service {
	return &Service{repo: NewRepo(runtime)}
}
