<!-- Code generated by goweb-scaffold. DO NOT EDIT. -->
<script lang="ts" setup>
import type { VxeTableGridOptions } from '#/adapter/vxe-table';
import type { DemoNoticeApi } from '#/api/demo_notice';

import { onMounted, ref } from 'vue';
import { useRoute } from 'vue-router';

import { Page, VbenButton, VbenButtonGroup, useVbenDrawer } from '@vben/common-ui';
import { Plus, X } from '@vben/icons';
import { InputSearch, message, Popconfirm, Tag } from 'ant-design-vue';

import { useVbenVxeGrid } from '#/adapter/vxe-table';
import {
  deleteDemoNotice,
  getDemoNoticeDetail,
  getDemoNoticeList,
} from '#/api/demo_notice';

import {
  getDemoNoticeStatusOptions,
  useColumns,
  useSearchFormSchema,
  searchFormFields,
} from './data';
import FormDrawerComponent from './modules/form-drawer.vue';

const selectedCount = ref(0);
const searchValue = ref('');
const route = useRoute();
const statusOptions = getDemoNoticeStatusOptions();

const getSelectedRecords = (): DemoNoticeApi.DemoNotice[] => {
  return (gridApi.grid?.getCheckboxRecords() as DemoNoticeApi.DemoNotice[]) || [];
};

const updateSelectedCount = () => {
  requestAnimationFrame(() => {
    selectedCount.value = getSelectedRecords().length;
  });
};

const resolveOption = (options: Array<{ color?: string; label: string; value: any }>, value: any) => {
  return options.find((item) => String(item.value) === String(value));
};

const onClearSearch = () => {
  searchValue.value = '';
  onRefresh();
};

const onSearch = (value: string) => {
  searchValue.value = value;
  onRefresh();
};

const [FormDrawer, formDrawerApi] = useVbenDrawer({
  connectedComponent: FormDrawerComponent,
  destroyOnClose: true,
});

const [Grid, gridApi] = useVbenVxeGrid({
  formOptions: {
    collapsed: true,
    schema: useSearchFormSchema(),
    showCollapseButton: true,
    submitOnChange: false,
    submitOnEnter: false,
  },
  gridOptions: {
    columns: useColumns(),
    keepSource: true,
    pagerConfig: {
      enabled: true,
    },
    proxyConfig: {
      ajax: {
        query: async ({ page, sort }, formValues) => {
          return await getDemoNoticeList({
            filter: JSON.stringify(formValues ?? {}),
            page: page.currentPage,
            page_size: page.pageSize,
            search: searchValue.value || undefined,
            sort_by: sort.field ? String(sort.field) : 'id',
            sort_order: sort.order === 'asc' ? 'asc' : 'desc',
          });
        },
      },
      sort: true,
    },
    rowConfig: {
      isHover: true,
      keyField: 'id',
    },
    sortConfig: {
      remote: true,
      trigger: 'cell',
    },
    stripe: false,
    toolbarConfig: {
      custom: true,
      refresh: true,
      zoom: true,
    },
    checkboxConfig: {
      highlight: true,
      reserve: true,
      trigger: 'row',
    },
  } as VxeTableGridOptions,
  gridEvents: {
    checkboxAll: updateSelectedCount,
    checkboxChange: updateSelectedCount,
  },
});

const onRefresh = () => {
  gridApi.grid?.clearCheckboxRow();
  gridApi.query();
  selectedCount.value = 0;
};

const onEdit = async (row: DemoNoticeApi.DemoNotice) => {
  const detail = await getDemoNoticeDetail(row.id);
  formDrawerApi.setData(detail).open();
};

const onCreate = () => {
  formDrawerApi.setData({}).open();
};

const onDelete = (row?: DemoNoticeApi.DemoNotice) => {
  let ids: number[] = [];

  if (row) {
    ids = [row.id];
  } else {
    const selectRecords = getSelectedRecords();
    if (selectRecords.length === 0) {
      message.warning('请选择要删除的数据');
      return;
    }
    ids = selectRecords.map((item) => item.id);
  }

  const hideLoading = message.loading({
    content: '删除中...',
    duration: 0,
    key: 'action_process_msg',
  });
  deleteDemoNotice({ ids })
    .then(() => {
      message.success({
        content: '删除成功',
        key: 'action_process_msg',
      });
      onRefresh();
    })
    .catch(() => {
      hideLoading();
    });
};

onMounted(() => {
  const formValues: Record<string, any> = {};
  for (const [key, value] of Object.entries(route.query)) {
    if (searchFormFields.includes(key) && value) {
      formValues[key] = Array.isArray(value) ? value[0] : value;
    }
  }
  if (Object.keys(formValues).length > 0) {
    gridApi.formApi.setValues(formValues);
    gridApi.query();
  }
});
</script>

<template>
  <Page>
    <FormDrawer @success="onRefresh" />
    <Grid>
      <template #status="{ row }">
        <Tag :color="resolveOption(statusOptions, row.status)?.color">
          {{ resolveOption(statusOptions, row.status)?.label ?? row.status }}
        </Tag>
      </template>
      <template #operation="{ row }">
        <VbenButtonGroup border>
          <VbenButton variant="icon" @click="onEdit(row)">
            编辑
          </VbenButton>
          <Popconfirm title="确认删除这条数据吗？" @confirm="onDelete(row)">
            <VbenButton variant="icon" status="danger">
              删除
            </VbenButton>
          </Popconfirm>
        </VbenButtonGroup>
      </template>
      <template #toolbar-actions>
        <VbenButton class="mr-3" size="sm" variant="outline" @click="onCreate">
          <Plus class="size-3" />
          新增演示公告
        </VbenButton>
        <VbenButtonGroup v-show="selectedCount > 0" border>
          <Popconfirm title="确认删除选中的数据吗？" @confirm="onDelete()">
            <VbenButton variant="outline">
              <X class="size-3" />
              删除
            </VbenButton>
          </Popconfirm>
        </VbenButtonGroup>
      </template>
      <template #toolbar-tools>
        <InputSearch
          allow-clear
          placeholder="请输入关键词"
          @clear="onClearSearch"
          @search="onSearch"
        />
      </template>
    </Grid>
  </Page>
</template>
