// Code generated by goweb-scaffold. DO NOT EDIT.

import { requestClient } from '#/api/request';

export namespace DemoNoticeApi {
  export interface DemoNotice {
    [key: string]: any;
    id: number;
    title: string;
    content: string;
    status: number;
    sort: number;
    created_at: number;
    updated_at: number;
    deleted_at: number;
  }

  export interface ListParams {
    page: number;
    page_size: number;
    search?: string;
    filter?: string;
    sort_by?: string;
    sort_order?: 'asc' | 'desc';
  }

  export interface ListResponse {
    list: DemoNotice[];
    total: number;
    page: number;
    limit: number;
  }
}

function toUnixTimestamp(value?: null | number | string) {
  if (!value) {
    return 0;
  }
  if (typeof value === 'number') {
    return value > 1_000_000_000_000 ? Math.floor(value / 1000) : value;
  }
  const timestamp = Date.parse(value);
  return Number.isNaN(timestamp) ? 0 : Math.floor(timestamp / 1000);
}

function normalizeDemoNotice(row: Record<string, any>): DemoNoticeApi.DemoNotice {
  return {
    id: Number(row.id ?? 0),
    title: row.title ?? '',
    content: row.content ?? '',
    status: Number(row.status ?? 0),
    sort: Number(row.sort ?? 0),
    created_at: toUnixTimestamp(row.created_at),
    updated_at: toUnixTimestamp(row.updated_at),
    deleted_at: toUnixTimestamp(row.deleted_at),
  };
}

async function getDemoNoticeList(params: DemoNoticeApi.ListParams) {
  const response = await requestClient.get<{
    limit?: number;
    list?: Array<Record<string, any>>;
    page?: number;
    total?: number;
  }>('/app/demo_notice/list', { params });
  return {
    limit: Number(response?.limit ?? params.page_size ?? 10),
    list: (response?.list ?? []).map(normalizeDemoNotice),
    page: Number(response?.page ?? params.page ?? 1),
    total: Number(response?.total ?? 0),
  } satisfies DemoNoticeApi.ListResponse;
}

async function getDemoNoticeDetail(id: number) {
  const response = await requestClient.get<Record<string, any>>('/app/demo_notice/detail', {
    params: { id },
  });
  return normalizeDemoNotice(response ?? {});
}

async function saveDemoNotice(
  id: number,
  data: Partial<DemoNoticeApi.DemoNotice>,
) {
  const payload: Record<string, any> = {
    title: data.title,
    content: data.content,
    status: data.status,
    sort: data.sort,
  };
  if (id > 0) {
    payload.id = id;
  }
  return requestClient.post('/app/demo_notice/save', payload);
}

async function deleteDemoNotice(data: { ids: number[] }) {
  return requestClient.post('/app/demo_notice/delete', data);
}

export { deleteDemoNotice, getDemoNoticeDetail, getDemoNoticeList, saveDemoNotice };
